### PR TITLE
feat: login page

### PR DESCRIPTION
**Pull request by yohanesray**
### What's added and updated

- add login page for mobile
- add login page for tablet
- add login page for desktop

### Figma

TBU

#### Desktop

image

#### Tablet

image

#### Mobile

image

### CODE REVIEW

**Comment by bryanprimus** [comment]
i think footer should have border top as well

**Comment by JoseLumbantobing** [comment]
For tablet and mobile mode, I think the hamburger menu is better positioned
on the right so that it doesn't clash with the app logo

Pada tanggal Sab, 29 Apr 2023 pukul 15.00 Yohanes R F Silitonga <
***@***.***> menulis:

**Comment by bryanprimus** [comment]
i agree with @JoseLumbantobing . we can remove the register button, and move hamburger to the right side

**Comment by yohanesray** [comment]
ok. is this better?

image

image

image



@JoseLumbantobing
@bryanltobing

**Comment by bryanprimus** [comment]
looking good @yohanesray21

**Comment by JoseLumbantobing** [comment]
for the footer there are fb and twitter logos, what is the purpose? I personally think it's not necessary because it can be added later on the website page. And maybe the footer can be made in the center not on the left.

**Comment by yohanesray** [comment]
> for the footer there are fb and twitter logos, what is the purpose? I personally think it's not necessary because it can be added later on the website page. And maybe the footer can be made in the center not on the left.

for the logo is not mandatory, and for its implementation it is still not implemented. I agree if the social media icon is not used first.

**Comment by JoseLumbantobing** [comment]
That's just my humble opinion, the rest looks good. Thankyou @yohanesray21

**Comment by yohanesray** [comment]
all concerns have been addressed here https://github.com/atletio/atletio.one/pull/1/commits/0d8e8c5fc3d7593bc69326ae65f325f30415254f

Kindly review again. Thank you @JoseLumbantobing @bryanltobing

**Review by JoseLumbantobing — APPROVED** [review]

**Review by bryanprimus — APPROVED** [review]
lgtm

**Pull request merged**
